package com.seoaudit.app.core.domain.model

/**
 * Represents the type of a line in a diff.
 */
enum class DiffLineType { ADD, REMOVE, CONTEXT }

/**
 * Represents a single line in a diff hunk.
 *
 * @param type Whether this line is added, removed, or context
 * @param content The text content of the line
 * @param lineNumber The line number in the original or modified file
 */
data class DiffLine(
    val type: DiffLineType,
    val content: String,
    val lineNumber: Int
)

/**
 * Represents a contiguous block of changes in a diff.
 *
 * @param oldStart Starting line number in the original file
 * @param oldLines Number of lines from original in this hunk
 * @param newStart Starting line number in the modified file
 * @param newLines Number of lines from modified in this hunk
 * @param lines The individual diff lines in this hunk
 */
data class DiffHunk(
    val oldStart: Int,
    val oldLines: Int,
    val newStart: Int,
    val newLines: Int,
    val lines: List<DiffLine>
)

/**
 * Represents the complete result of a diff operation.
 *
 * @param hunks List of change hunks
 * @param additions Total number of added lines
 * @param deletions Total number of deleted lines
 */
data class DiffResult(
    val hunks: List<DiffHunk>,
    val additions: Int,
    val deletions: Int
)

/**
 * Represents a code fix generated by the AI engine.
 *
 * @param issueId ID of the audit issue this fix addresses
 * @param originalCode The original source code
 * @param proposedCode The proposed fixed code
 * @param diff The diff between original and proposed
 * @param explanation Human-readable explanation of the fix
 * @param isValid Whether the fix passed validation
 * @param validationErrors List of validation errors if any
 */
data class CodeFix(
    val issueId: String,
    val originalCode: String,
    val proposedCode: String,
    val diff: DiffResult,
    val explanation: String,
    val isValid: Boolean,
    val validationErrors: List<String> = emptyList()
)
